BookStoreWeb/Controllers/ChangePasswordController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
	public class ChangePasswordController : Controller
	{
		// GET: ChangePasswordController
		public ActionResult Index()
		{

			return View();
		}

		// GET: ChangePasswordController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: ChangePasswordController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ChangePasswordController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ChangePasswordController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: ChangePasswordController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(String oldPass, String newPass, String renewPass)
		{
			User? curUser = new User();
			string? sesUser = HttpContext.Session.GetString("user");
			if (sesUser != null)
			{
				curUser = JsonConvert.DeserializeObject<User>(sesUser);
			}
			using Prn211Context context = new Prn211Context();
			if(newPass != renewPass)
			{
				TempData["message"] = "The new password and the confirm new password are not the same!";
				return RedirectToAction("Index");
			} else if (oldPass.Equals(curUser.Password))
			{
				curUser.Password = newPass;
				context.Users.Update(curUser);
				context.SaveChanges();
				HttpContext.Session.SetString("user", JsonConvert.SerializeObject(curUser));
				TempData["message"] = "Change password successfully!";
				return RedirectToAction("Index");
			} else
			{
				TempData["message"] = "The old password is incorrect!";
				return RedirectToAction("Index");
			}
		}

		// GET: ChangePasswordController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ChangePasswordController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

BookStoreWeb/Controllers/UserProfileController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
	public class UserProfileController : Controller
	{
		// GET: UserProfileController
		public ActionResult Index()
		{
			User? curUser = new User();
			string? user = HttpContext.Session.GetString("user");
			if (user != null)
			{
				curUser = JsonConvert.DeserializeObject<User>(user);
			}
			return View(curUser);
		}

		// GET: UserProfileController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: UserProfileController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: UserProfileController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: UserProfileController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: UserProfileController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(User user)
		{
			using Prn211Context context = new Prn211Context();
			User oldUser = context.Users.SingleOrDefault(x=>x.UserId == user.UserId);
			oldUser.Name = user.Name;
			oldUser.Address = user.Address;
			oldUser.Phone = user.Phone;
			context.Users.Update(oldUser);
			context.SaveChanges();
			HttpContext.Session.SetString("user", JsonConvert.SerializeObject(oldUser));
			return RedirectToAction("Index");
		}

		// GET: UserProfileController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: UserProfileController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

BookStoreWeb/Views/UserProfile/Index.cshtml
@model User
<div id="main">
<div class="inner">
							<section>
								<h2>Profile</h2>

								<form method="post" asp-action="Edit">
									<div class="fields">
										<div class="field half">
											<input asp-for="Name" type="text" name="name" id="name" value="@Model.Name" />
										</div>

										<div class="field half">
											<input asp-for="Address" type="text" name="address" id="address" value="@Model.Address" />
										</div>

										<div class="field half">
											<input asp-for="Phone" type="text" name="phone" id="phone" value="@Model.Phone" />
										</div>
											<input asp-for="UserId" type="hidden" value="@Model.UserId"/>
										<div class="field text-right">
											<label>&nbsp;</label>

											<ul class="actions">
												<li><input type="submit" value="Update Profile" class="primary" /></li>
											</ul>
											<ul class="actions">
												<li><input asp-controller="ChangePassword" asp-action="Index" type="submit" value="Change Password" class="primary" /></li>
											</ul>
										</div>
									</div>
								</form>
							</section>
							<section>

								<h2>Share This</h2>

								<ul class="icons">
									<li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon style2 fa-linkedin"><span class="label">LinkedIn</span></a></li>
									<li><a href="#" class="icon style2 fa-behance"><span class="label">Behance</span></a></li>
								</ul>
							</section>
						</div></div>