BookStoreWeb/Controllers/AuthController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Login()
        {
            if (HttpContext.Session.GetString("user") != null) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User user)
        {
            using Prn211Context context = new Prn211Context();
            User? userInfo = context.Users.SingleOrDefault(u => u.Email.Equals(user.Email) && u.Password.Equals(user.Password));
            if (userInfo == null)
            {
                TempData["message"] = "The email or password is incorrect!";
                return RedirectToAction("Login");
            }
            if (userInfo.Status == 0)
            {
                TempData["message"] = "You are banned!";
                return RedirectToAction("Login");
            }
            HttpContext.Session.SetString("user", JsonConvert.SerializeObject(userInfo));
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(User user)
        {
            using Prn211Context context = new Prn211Context();
            if (HttpContext.Session.GetString("user") != null) return RedirectToAction("Index", "Home");
            if (context.Users.SingleOrDefault(u => u.Email.Equals(user.Email)) != null)
            {
                TempData["message"] = "The email already exists!";
                return RedirectToAction("Login");
            }
            user.Status = 1;
            user.Role = 1;
            context.Add(user);
            context.SaveChanges();
            TempData["message"] = "Register sucessfully!";
            return RedirectToAction("Login");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

BookStoreWeb/Controllers/CartController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add(int productID)
        {
            using Prn211Context context = new Prn211Context();
            List<Cart>? carts = new List<Cart>();
            string? cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(cartString);
            }
            bool found = false;
            foreach (Cart cart in carts)
            {
                if (cart.Product.ProductId == productID) { cart.Quantity++; found = true; }
            }
            if (!found)
            {

                Product product = context.Products.SingleOrDefault(pro => pro.ProductId == productID);
                product.Category = context.Categories.Find(product.CategoryId);
                carts.Add(new Cart
                {
                    Product = product,
                    Quantity = 1
                });
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult ChangeQuantity(int id, int quantity)
        {
            List<Cart>? carts = new List<Cart>();
            string? cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(cartString);
            }
            foreach (Cart cart in carts)
            {
                if (cart.Product.ProductId == id)
                {
                    if (quantity == 0)
                    {
                        carts.Remove(cart);
                    }
                    else cart.Quantity = quantity;
                }
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            return Json("Change quantity successfully");
        }
    }
}

BookStoreWeb/Controllers/OrderController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
    public class OrderController : Controller
    {
        public IActionResult Index()
        {
            using Prn211Context context = new Prn211Context();
            string? userString = HttpContext.Session.GetString("user");
            if (userString == null) return RedirectToAction("Index", "Home");
            User user = JsonConvert.DeserializeObject<User>(userString);
            List<Order> orders = context.Orders.Include(o => o.OrderDetails).Where(order => order.UserId == user.UserId).ToList();
            List<Product> products = context.Products.ToList();
            ViewBag.Products = products;
            return View(orders);
        }

        public IActionResult Details(int id)
        {
            using Prn211Context context = new Prn211Context();
            Order order = context.Orders.Find(id);
            List<OrderDetail> orderDetails = context.OrderDetails.Where(orderdetail => orderdetail.OrderId == id).ToList();
            List<Tuple<OrderDetail, Product>> detailsWithProduct = new List<Tuple<OrderDetail, Product>>();
            foreach (OrderDetail orderDetail in orderDetails)
            {
                detailsWithProduct.Add(new Tuple<OrderDetail, Product>(orderDetail, context.Products.Include(p => p.Category).SingleOrDefault(p => p.ProductId == orderDetail.ProductId)));
            }
            ViewBag.order = order;
            ViewData["detailsWithProduct"] = detailsWithProduct;
            return View();

        }

        public IActionResult Checkout()
        {
            string cartString = HttpContext.Session.GetString("cart");
            if (cartString == null)
            {
                return RedirectToAction("Index", "Product");
            }
            else
            {
                User user;
                try
                {
                    user = JsonConvert.DeserializeObject<User>(HttpContext.Session.GetString("user"));
                }
                catch (NullReferenceException ex)
                {
                    return RedirectToAction("Login", "Auth");
                }
                using Prn211Context context = new Prn211Context();
                Order order = new Order
                {
                    UserId = user.UserId,
                    OrderedDate = DateTime.Now,
                    Status = 1
                };
                context.Add(order);
                context.SaveChanges();
                int orderID = context.Orders.Max(o => o.OrderId);
                List<Cart> carts = JsonConvert.DeserializeObject<List<Cart>>(cartString);
                foreach (Cart cart in carts)
                {
                    context.Add(new OrderDetail
                    {
                        OrderId = orderID,
                        ProductId = cart.Product.ProductId,
                        Price = cart.Product.Price,
                        Quantity = cart.Quantity
                    });
                    context.SaveChanges();
                }
                HttpContext.Session.Remove("cart");
            }
            return RedirectToAction("Index");
        }

        public IActionResult ChangeStatus(int id, int status)
        {
            using Prn211Context context = new Prn211Context();
            Order order = context.Orders.Find(id);
            if ((order.Status == 1 && status == 0) || (order.Status == 2 && status == 3))
            {
                order.Status = status;
            }
            context.Entry<Order>(order).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BookStoreWeb/Controllers/UserProfileController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
	public class UserProfileController : Controller
	{
		// GET: UserProfileController
		public ActionResult Index()
		{
			User? curUser = new User();
			string? user = HttpContext.Session.GetString("user");
			if (user != null)
			{
				curUser = JsonConvert.DeserializeObject<User>(user);
			}
			return View(curUser);
		}

		// GET: UserProfileController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: UserProfileController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: UserProfileController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: UserProfileController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: UserProfileController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(User user)
		{
			using Prn211Context context = new Prn211Context();
			User oldUser = context.Users.SingleOrDefault(x=>x.UserId == user.UserId);
			oldUser.Name = user.Name;
			oldUser.Address = user.Address;
			oldUser.Phone = user.Phone;
			context.Users.Update(oldUser);
			context.SaveChanges();
			HttpContext.Session.SetString("user", JsonConvert.SerializeObject(oldUser));
			return RedirectToAction("Index");
		}

		// GET: UserProfileController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: UserProfileController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

BookStoreWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/BookStoreWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <noscript><link rel="stylesheet" href="~/css/noscript.css" /></noscript>
</head>
<body>
    <div id="wrapper">
        <header id="header">
            <div class="inner">
                <a asp-action="Index" asp-controller="Home" class="logo">
                    <span class="fa fa-book"></span> <span class="title">Book Online Store Website</span>
                </a>

                <nav>
                    <ul>
                        <li><a href="#menu">Menu</a></li>
                    </ul>
                </nav>

            </div>
        </header>

        <!-- Menu -->
        <nav id="menu">
            <h2>Menu</h2>
            <ul>
                <li><a asp-action="Index" asp-controller="Home">Home</a></li>

                @if (Accessor?.HttpContext?.Session.GetString("user") == null)
                {
                    <li><a asp-action="Login" asp-controller="Auth">Login</a></li>
                }
                else
                {
                    <li><a asp-action="Logout" asp-controller="Auth">Logout</a></li>
                }

                <li><a asp-action="Index" asp-controller="Product">Products</a></li>

                @if (Accessor?.HttpContext?.Session.GetString("user") != null)
                {
                    <li><a asp-action="Index" asp-controller="Order">Order History</a></li>
                }

                <li><a asp-action="Index" asp-controller="Cart">Checkout</a></li>

                @if (Accessor?.HttpContext?.Session.GetString("user") != null)
                {
                        <li><a asp-action="Index" asp-controller="UserProfile">Profile</a></li>
                }

            </ul>
        </nav>

        @RenderBody()

        <footer id="footer">
            <div class="inner">
                <section>
                    <h2>Contact Us</h2>
                    <form method="post" action="#">
                        <div class="fields">
                            <div class="field half">
                                <input type="text" name="name" id="name" placeholder="Name" />
                            </div>

                            <div class="field half">
                                <input type="text" name="email" id="email" placeholder="Email" />
                            </div>

                            <div class="field">
                                <input type="text" name="subject" id="subject" placeholder="Subject" />
                            </div>

                            <div class="field">
                                <textarea name="message" id="message" rows="3" placeholder="Notes"></textarea>
                            </div>

                            <div class="field text-right">
                                <label>&nbsp;</label>

                                <ul class="actions">
                                    <li><input type="submit" value="Send Message" class="primary" /></li>
                                </ul>
                            </div>
                        </div>
                    </form>
                </section>
                <section>
                    <h2>Contact Info</h2>

                    <ul class="alt">
                        <li><span class="fa fa-envelope-o"></span> <a href="#">contact@company.com</a></li>
                        <li><span class="fa fa-phone"></span> +1 333 4040 5566 </li>
                        <li><span class="fa fa-map-pin"></span> 212 Barrington Court New York, ABC 10001 United States of America</li>
                    </ul>

                    <h2>Follow Us</h2>

                    <ul class="icons">
                        <li><a href="#" class="icon style2 fa-twitter"><span class="label">Twitter</span></a></li>
                        <li><a href="#" class="icon style2 fa-facebook"><span class="label">Facebook</span></a></li>
                        <li><a href="#" class="icon style2 fa-instagram"><span class="label">Instagram</span></a></li>
                        <li><a href="#" class="icon style2 fa-linkedin"><span class="label">LinkedIn</span></a></li>
                    </ul>
                </section>

                <ul class="copyright">
                    <li>Copyright © 2020 Company Name </li>
                    <li>Template by: <a href="https://www.phpjabbers.com/">PHPJabbers.com</a></li>
                </ul>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.scrollex.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.scrolly.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookStoreWeb/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ProductAdmin" asp-action="Index">Manage Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserAdmin" asp-action="Index">Manage User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrderAdmin" asp-action="Index">Manage Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HomePage</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>