BookStoreWeb/Controllers/Admin/ProductAdminController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.IO;
using System.Linq;

namespace BookStoreWeb.Controllers.Admin
{
    public class ProductAdminController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ProductAdminController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: ProductAdminController
        public ActionResult Index(string SearchString, int ProductCategory)
        {
            using var context = new Prn211Context();
            var products = context.Products.Include(pro => pro.Category).ToList();

            if (!string.IsNullOrEmpty(SearchString))
            {
                products = products.Where(pro => pro.Name.ToLower().Contains(SearchString.ToLower())).ToList();
            }

            if (ProductCategory != 0)
            {
                products = products.Where(pro => pro.CategoryId == ProductCategory).ToList();
            }
            return View(products);
        }

        // GET: ProductAdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductAdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product pro, IFormFile file)
        {
            try
            {
                if (file != null && file.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                    var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "images", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(stream);
                    }
                    pro.Img = "images/" + fileName;
                }

                using (var context = new Prn211Context())
                {
                    context.Products.Add(pro);
                    context.SaveChanges();
                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return View(pro);
            }
        }

        // GET: ProductAdminController/Edit/5
        public ActionResult Edit(int proId)
        {
            Product pro = GetProductByID(proId);
            if (pro == null) return NotFound();
            ViewBag.CategoryId = pro.CategoryId;
            return View(pro);
        }

        // POST: ProductAdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product pro)
        {
            try
            {
                using var context = new Prn211Context();
                context.Products.Update(pro);
                context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        public Product GetProductByID(int id)
        {
            Product u = null;
            try
            {
                using var context = new Prn211Context();
                u = context.Products.Include(pro => pro.Category).FirstOrDefault(pro => pro.ProductId == id);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            return u;
        }
    }
}

BookStoreWeb/Views/ProductAdmin/Create.cshtml
@model BookStoreWeb.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input type="file" id="uploadImg" name="file" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input asp-for="Img" class="form-control" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control">
                    <option value="1" selected="@(ViewBag.CategoryId == 1 ? "selected" : null)">Fiction</option>
                    <option value="2" selected="@(ViewBag.CategoryId == 2 ? "selected" : null)">Non-Fiction</option>
                    <option value="3" selected="@(ViewBag.CategoryId == 3 ? "selected" : null)">Novel</option>
                    <option value="4" selected="@(ViewBag.CategoryId == 4 ? "selected" : null)">Comic</option>
                    <option value="5" selected="@(ViewBag.CategoryId == 5 ? "selected" : null)">Travel</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreWeb/Views/ProductAdmin/Edit.cshtml
@model BookStoreWeb.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Img" class="control-label"></label>
                <input asp-for="Img" class="form-control" />
                <span asp-validation-for="Img" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desc" class="control-label"></label>
                <input asp-for="Desc" class="form-control" />
                <span asp-validation-for="Desc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control">
                    <option value="1" selected="@(ViewBag.CategoryId == 1 ? "selected" : null)">Fiction</option>
                    <option value="2" selected="@(ViewBag.CategoryId == 2 ? "selected" : null)">Non-Fiction</option>
                    <option value="3" selected="@(ViewBag.CategoryId == 3 ? "selected" : null)">Novel</option>
                    <option value="4" selected="@(ViewBag.CategoryId == 4 ? "selected" : null)">Comic</option>
                    <option value="5" selected="@(ViewBag.CategoryId == 5 ? "selected" : null)">Travel</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreWeb/Views/ProductAdmin/Index.cshtml
@model IEnumerable<BookStoreWeb.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Manage Product</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="ProductAdmin" asp-action="Index" method="get">
    <p>
        <select name="ProductCategory">
            <option value="">All</option>
            <option value="1">Fiction</option>
            <option value="2">Non-Fiction</option>
            <option value="3">Novel</option>
            <option value="4">Comic</option>
            <option value="5">Travel</option>
        </select>   

        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Img)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Img)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-proId="@item.ProductId">Edit</a> 
                    @* <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a> *@
                </td>
            </tr>
        }
    </tbody>
</table>