BookStoreWeb/Models/Product.cs
using System;
using System.Collections.Generic;

namespace BookStoreWeb.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string Name { get; set; } = null!;

    public int Quantity { get; set; }

    public decimal Price { get; set; }

    public string Img { get; set; } = null!;

    public int Status { get; set; }

    public string Desc { get; set; } = null!;

    public int CategoryId { get; set; }

    public virtual Category Category { get; set; } = null!;

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}

BookStoreWeb/Controllers/CartController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace BookStoreWeb.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Add(int productID)
        {
            using Prn211Context context = new Prn211Context();
            List<Cart>? carts = new List<Cart>();
            string? cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(cartString);
            }
            bool found = false;
            foreach (Cart cart in carts)
            {
                if (cart.Product.ProductId == productID) { cart.Quantity++; found = true; }
            }
            if (!found)
            {

                Product product = context.Products.SingleOrDefault(pro => pro.ProductId == productID);
                product.Category = context.Categories.Find(product.CategoryId);
                carts.Add(new Cart
                {
                    Product = product,
                    Quantity = 1
                });
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult ChangeQuantity(int id, int quantity)
        {
            List<Cart>? carts = new List<Cart>();
            string? cartString = HttpContext.Session.GetString("cart");
            if (cartString != null)
            {
                carts = JsonConvert.DeserializeObject<List<Cart>>(cartString);
            }
            foreach (Cart cart in carts)
            {
                if (cart.Product.ProductId == id)
                {
                    if (quantity == 0)
                    {
                        carts.Remove(cart);
                    }
                    else cart.Quantity = quantity;
                }
            }
            HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(carts, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            }));
            return Json("Change quantity successfully");
        }
    }
}

BookStoreWeb/Controllers/ProductController.cs
using BookStoreWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStoreWeb.Controllers
{
	public class ProductController : Controller
	{
		// GET: ProductController
		[Route("Product/{page=1}")]
		public ActionResult Index(int page, string txtSearch = "")
		{
			using Prn211Context context = new Prn211Context();
			List<Product> products = context.Products.Where(product => product.Name.Contains(txtSearch.Trim())).ToList();
			ViewBag.CurrentPage = page;
			ViewBag.TotalPage = (products.Count() - 1) / 6 + 1;
			return View(products.Skip((page - 1) * 6).Take(6).ToList());
		}

		// GET: ProductController/Details/5
		public ActionResult Details(int id)
		{
			using Prn211Context context = new Prn211Context();
			var product = context.Products.Include(p => p.Category).FirstOrDefault(x=>x.ProductId == id);
			ViewBag.Product = product;
			var products = context.Products.ToList();
			List<Product> productsList = (from p in products
										 where p.CategoryId==product.CategoryId && p.ProductId!=product.ProductId
										 select p).Take(3).ToList();
			return View(productsList);
		}

		// GET: ProductController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ProductController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ProductController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: ProductController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ProductController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ProductController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

BookStoreWeb/Views/Product/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Product pro = ViewBag.Product;
}
@model List<BookStoreWeb.Models.Product>


<div id="main">
    <div class="inner">
        <h1>@pro.Name <span class="pull-right"> $@pro.Price.ToString("0.00")</span></h1>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-5">
                    <img src="~/@pro.Img" class="img-fluid" alt="" style="width:100%">
                </div>

                <div class="col-md-7">
                    <p><h3 style="display: inline-block;">Category:</h3> @pro.Category.Name</p>
                    <p>@pro.Desc</p>                   

                    <div class="row">
                        @* <div class="col-sm-4">
                        <label class="control-label">Extra 1</label>

                        <div class="form-group">
                        <select>
                        <option value="0">Extra 1</option>
                        <option value="1">Extra 2</option>
                        <option value="2">Extra 3</option>
                        </select>
                        </div>
                        </div> *@

                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-6">
                                    <a asp-action="Add" asp-controller="Cart" asp-route-productID="@pro.ProductId"><input type="submit" value="Add to Cart" /></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <br>
        <br>

        <div class="container-fluid">
            <h2 class="h2">Similar Products</h2>

            <!-- Products -->
            <section class="tiles">
                @foreach (var item in Model)
                {
                    <article class="style1">
                        <span class="image">
                            <img src="~/@item.Img" alt="" />
                        </span>
                        <a href="details?id=@item.ProductId">
                            <h2>@item.Name</h2>

                            <p><strong>$@item.Price</strong></p>

                            <p>@item.Desc</p>
                        </a>
                    </article>

                }
            </section>
        </div>
    </div>
</div>

BookStoreWeb/Views/Product/Index.cshtml
@model IEnumerable<Product>

<div id="main">
    <div class="inner">
        <h1>Products</h1>
        <!-- Banner -->
        <div class="image main">
            <img src="~/images/banner-image-6-1920x500.jpg" class="img-fluid" alt="" />
        </div>

        <!-- Search -->
        <div id="search">
            <form asp-action="Index" method="get" style="display: flex;justify-content: space-between;">
                <input name="txtSearch" type="text" class="textbox" placeholder="Search" style="width: 93%;">
                <button type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
            </form>
        </div>
        
        <!-- Products -->
        <section class="tiles">
            @foreach (var (product, index) in Model.Select((value, i) => (value, i)))
            {
                <article class="@("style"+index)">
                    <span class="image">
                        <img src="@product.Img" alt="@product.Name" />
                    </span>
                    <a asp-action="Details" asp-controller="Product" asp-route-id="@product.ProductId">
                        <h2>@product.Name</h2>

                        <p><strong>$@product.Price.ToString("0.00")</strong></p>

                        <p style="overflow: hidden; text-overflow: ellipsis;">@product.Desc</p>
                    </a>
                </article>
            }
        </section>

        <!--Navigation-->
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @{
                    int page = ViewBag.CurrentPage;
                }
                <li class="page-item @(page < 2 ? "disabled" : "")">
                    <a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page-1)" tabindex="-1" aria-disabled="@(page < 2)"><<</a>
                </li>
                @if (page > 2 && ViewBag.TotalPage > 3)
                {
                    <li class="page-item">...</li>
                }
                @if (page > 1)
                {
                    if (page == 3 && ViewBag.TotalPage < 4)
                    {
                        <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page-2)">@(page - 2)</a></li>
                    }
                    <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page-1)">@(page - 1)</a></li>
                }
                <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page)">@(page)</a></li>
                @if (page < ViewBag.TotalPage)
                {
                    <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page+1)">@(page + 1)</a></li>
                    if (page == 1 && ViewBag.TotalPage < 4)
                    {
                        <li class="page-item"><a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@(page+2)">@(page + 2)</a></li>
                    }
                }
                @if (page < ViewBag.TotalPage - 1 && ViewBag.TotalPage > 3)
                {
                    <li class="page-item">...</li>
                }
                <li class="page-item @(page >= ViewBag.TotalPage ? "disabled" : "")">
                    <a class="page-link" asp-action="Index" asp-controller="Product" asp-route-page="@ViewBag.TotalPage" tabindex="-1" aria-disabled="@(page >= ViewBag.TotalPage)">>></a>
                </li>
            </ul>
        </nav>
    </div>
</div>